### ISSUE TITLE
Make debug runtime configurable

### ISSUE THREAD

**Issue by margau** [rgot-org/TheThingsNetwork_esp32#10]
Hello together,
I have a use case where I will need a relatively clean Serial Port - therefore I need to disable the Debug output.
The DEBUG-Flag is currently set at compile time, so I'd suggest to move this flag into a runtime variable to avoid messing with defines inside the library. 
What are the opinions about this?
I could probably prepare a PR about this, if there are no contrary opinions.

Best regards
margau

**Comment by rgot-org** [comment]
correct in last commit.
