### ISSUE TITLE
missing BLEDevice.h

### ISSUE THREAD

**Issue by somervda** [rgot-org/TheThingsNetwork_esp32#16]
Hi Francois

Nice library , I am just getting started with a Heltec board and Lorawa. One issue I ran into is shown below. When I didn't want to implement the BLE functionality, the TTN_BLE_esp32.h was still looking for a BLEDevice.h file during the compile. For now I have removed the TTN_BLE_esp32 files from my copy of the libraries.

     In file included from .pio\libdeps\heltec_wifi_lora_32_V2\TTN_esp32\src\TTN_BLE_esp32.cpp:1:0:
     .pio\libdeps\heltec_wifi_lora_32_V2\TTN_esp32\src\TTN_BLE_esp32.h:16:23: fatal error: BLEDevice.h: No such file or directory

**Comment by rgot-org** [comment]
hello, 
if you don't need to use BLE, simply remove the line `#include "TTN_BLE_esp32.h"` at the top of the ino file.

In your error message, it seems that BLEDevice.h is not found, this library is installed with the board manager when installing the esp32 board. TTN_BLE_esp32 dépends  on board esp32 v1.0.4 and higher

**Comment by somervda** [comment]
Thanks
