### ISSUE TITLE
Typo in TTN_esp32.cpp

### ISSUE THREAD

**Issue by somervda** [rgot-org/TheThingsNetwork_esp32#17]
Hi Francois

Looks like there is a typo in line 245 of TTN_esp32.cpp. When I turn on the DEBUG flag in the library the compiler complains about the ESP-LOGI object not being defined. I changed it to ESP_LOGI and all works now.

    bool TTN_esp32::personalize(const char* devAddr, const char* nwkSKey, const char* appSKey)
    {
        ByteArrayUtils::hexStrToBin(nwkSKey, net_session_key, 16);
        ByteArrayUtils::hexStrToBin(appSKey, app_session_key, 16);
        ByteArrayUtils::hexStrToBin(devAddr, dev_adr, 4);
        devaddr_t dev_addr = dev_adr[0] << 24 | dev_adr[1] << 16 | dev_adr[2] << 8 | dev_adr[3];
    #ifdef DEBUG
        ESP-LOGI(TAG,"Dev adr str: %s", devAddr);
        ESP_LOGI(TAG,"Dev adr int: %X", dev_addr);
    #endif // DEBUG
        personalize(0x13, dev_addr, net_session_key, app_session_key);
        return true;
    }

**Comment by rgot-org** [comment]
thank's
