### ISSUE TITLE
How i select subband in AU915?? 

### ISSUE THREAD

**Issue by erdmanncross** [rgot-org/TheThingsNetwork_esp32#2]
I am testing this lib.
but I can't find where I can select the subband in the Au915 band
because TTN uses the second band
https://www.thethingsnetwork.org/docs/lorawan/frequency-plans.html#au915-928
i changed lorabase_au915.h to init in same frequency 916.8

**Comment by rgot-org** [comment]
please can you test to change the config in the **project_config\lmic_project_config.h** file.
i've not tested for other band than EU868.
